services:
  pyshacl:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/data:/data
    ports:
      - "5000:5000"  # Expose port 5000
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - pyshacl 